"DiametralPitch"= 1
"NumTeeth"= 52
"PressureAngle"= 25deg
"Addendum"= 1 / "DiametralPitch"
"Dedendum"= 1.25 / "DiametralPitch"
"WorkingDepth"= 2 / "DiametralPitch"
"WholeDepth"= 2.25 / "DiametralPitch"
"Clearance"= 0.25 / "DiametralPitch"
"ToothThickness"= 1.5708 / "DiametralPitch"
"CircularPitch"= pi / "DiametralPitch"
"PitchCircle"= "NumTeeth" / "DiametralPitch"
"OutsideDiameter"= ( "NumTeeth" + 2 ) / "DiametralPitch"
"Fillet"= "Clearance" * cos ( "PressureAngle" ) * tan ( ( 90 + "PressureAngle" ) / 2 )
"AddendumCircle"= "PitchCircle" + ( 2 * "Addendum" )
"DedendumCircle"= "PitchCircle" - ( 2 * "Dedendum" )
"BaseCircle"= "PitchCircle" * cos ( "PressureAngle" )
"PitchAngle"= 360deg / "NumTeeth"
"Alpha"= sqr ( "PitchCircle" ^ 2 - "BaseCircle" ^ 2 ) / "BaseCircle" * 180 / PI - "PressureAngle"
"Beta"= ( "PitchAngle" / 4 - "Alpha" )
"Phi"= sqr ( ( "AddendumCircle" / 2 ) ^ 2 - ( "BaseCircle" / 2 ) ^ 2 ) / ( "BaseCircle" / 2 )
"D1@Sketch1"="RingOD"
"D1@Sketch2"="OutsideDiameter"
"D2@Sketch2"="PitchCircle"
"D3@Sketch2"="BaseCircle"
"D4@Sketch2"="DedendumCircle"
"RingOD"= ( "NumTeeth" + 6 ) / "DiametralPitch"
"sth_r"= sin ( 360 / "NumTeeth" )
"cth_r"= cos ( 360 / "NumTeeth" )
"D1@Sketch3"="tipDiameter"
"D1@Sketch5"="tipDiameter"
"D2@Sketch5"="OutsideDiameter"
"D3@Sketch5"="Fillet"
"D4@Sketch5"="Fillet"
"D5@Sketch5"="tipDiameter"/2
"tipDiameter"= "PitchCircle" - 2 * "Addendum"
"D1@CirPattern1"="NumTeeth"
"materialClearance"= 0.07'material clearance cut
"D1@Sketch7"="materialClearance"
"D1@Sketch8"="tipDiameter"+"materialClearance"*2
